name = main
src = $(wildcard *.cpp)
obj = $(src:/c=.o)

CC = g++
CFLAGS = -std=c++0x -03
LIBFLAGS = -lleda -lm

Leda = '/urs/local/LEDA/inc1'
LedaLibs = 'usr/local/LEDA'

all:#(name)
$(name): $(obj)
	$(CC) $(CFLAGS) -o $@ $^ -I$(Leda) -L$(LedaLibs) $(LIBFLAGS)

run:
	./$(name)

clean:
	rm -f $(name)